import {fixtures,sourceScore,linkClaims,findContradictions,coverage} from './engine.js';
const $=s=>document.querySelector(s),escapeHtml=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initial={project:{name:'Bay Area Housing Affordability',question:'How are Bay Area cities addressing housing affordability?',jurisdictions:['San Francisco','San José','Oakland'],startYear:2023},sources:structuredClone(fixtures.sources),claims:structuredClone(fixtures.claims),approved:false};
let state;try{state=JSON.parse(localStorage.getItem('policy-evidence-workspace'))||initial}catch{state=initial}
let linked=[],contradictions=[],cov;
const dimensions=['status','funding','outcomes'];
function persist(){localStorage.setItem('policy-evidence-workspace',JSON.stringify(state))}
function calculate(){linked=linkClaims(state.claims,state.sources);contradictions=findContradictions(state.claims);cov=coverage(state.claims,state.project.jurisdictions,dimensions,state.sources)}
function render(){calculate();const primary=state.sources.length?Math.round(100*state.sources.filter(s=>s.primary).length/state.sources.length):0,supported=linked.filter(c=>c.support!=='unsupported').length;
 $('#projectName').textContent=state.project.name;$('#questionTitle').textContent=state.project.question;$('#scopeLine').innerHTML=`${state.project.jurisdictions.map(escapeHtml).join(' · ')} <span>Since ${state.project.startYear}</span>`;$('#workflowStatus').textContent=state.approved?'Report approved':'Research in progress';$('#coverage').textContent=`${cov.percent}%`;$('#sideCoverage').textContent=`${cov.percent}%`;$('#coverageProgress').value=cov.percent;$('#coverageNote').textContent=`${cov.cells.filter(x=>x.covered).length} of ${cov.cells.length} required cells`;$('#primaryRatio').textContent=`${primary}%`;$('#supported').textContent=`${supported}/${linked.length}`;$('#supportNote').textContent=`${linked.length-supported} unsupported`;$('#contradictionsMetric').textContent=contradictions.length;$('#contradictionCount').textContent=contradictions.length;$('#sourceCount').textContent=state.sources.length;$('#claimCount').textContent=state.claims.length;$('#budgetSources').textContent=`${state.sources.length} / 20`;$('#sourceProgress').value=state.sources.length;
 $('#matrix').innerHTML=`<div class="matrix-row"><b>Jurisdiction</b>${dimensions.map(x=>`<b>${x}</b>`).join('')}</div>`+state.project.jurisdictions.map(j=>`<div class="matrix-row"><b>${escapeHtml(j)}</b>${dimensions.map(d=>{const x=cov.cells.find(c=>c.jurisdiction===j&&c.dimension===d);return `<button class="cell ${x?.covered?'covered':'missing'}" data-cell="${escapeHtml(j)}|${d}">${x?.covered?'✓ Covered':'＋ Add evidence'}</button>`}).join('')}</div>`).join('');
 $('#timeline').innerHTML=state.claims.length?state.claims.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(c=>`<button class="timeline-item" data-claim="${escapeHtml(c.id)}"><small>${escapeHtml(c.date.slice(0,7))}</small><i class="dot"></i><p><b>${escapeHtml(c.status.toUpperCase())} · ${escapeHtml(c.jurisdiction)}</b>${escapeHtml(c.subject)}</p></button>`).join(''):'<p class="empty">Add a claim to build the timeline.</p>';
 $('#claims').innerHTML=linked.length?linked.map(c=>{const s=c.evidence[0],q=s?sourceScore(s):{grade:'—'};return `<button class="claim" data-claim="${escapeHtml(c.id)}"><div><small>${escapeHtml(c.status.toUpperCase())} · ${escapeHtml(c.jurisdiction)} · ${escapeHtml(c.support)}</small><p>${escapeHtml(c.text)}</p><small>${s?`${escapeHtml(s.title)} · ${escapeHtml(s.locator)}`:'No supporting source'}</small></div><span class="grade">${q.grade}</span></button>`}).join(''):'<p class="empty">No evidence claims yet.</p>';
 $('#contradictions').innerHTML=contradictions.length?contradictions.map(x=>`<article><h2>${escapeHtml(x.subject)}</h2><div class="compare">${x.claims.map((c,i)=>`${i?'<span>≠</span>':''}<div><small>${escapeHtml(c.jurisdiction)}</small><strong>${escapeHtml(c.value)}</strong><p>${escapeHtml(c.text)}</p></div>`).join('')}</div><p class="note">${escapeHtml(x.summary)}</p><button data-review="${escapeHtml(x.subject)}">Review evidence</button></article>`).join(''):'<div class="no-conflict"><strong>✓ No contradictions detected</strong><p>Claims with the same metric currently agree.</p></div>';
 $('#sourceList').innerHTML=state.sources.length?state.sources.map(s=>{const q=sourceScore(s);return `<article><span class="grade">${q.grade}</span><div><b>${escapeHtml(s.title)}</b><p>${escapeHtml(s.publisher)} · ${escapeHtml(s.type)} · ${escapeHtml(s.locator)}</p></div><button data-remove-source="${escapeHtml(s.id)}">Remove</button></article>`}).join(''):'<p class="empty">No sources yet.</p>';bindRendered()}
function bindRendered(){document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>inspectClaim(b.dataset.claim));document.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{const [j,d]=b.dataset.cell.split('|');openClaim(j,d)});document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>showReport(true));document.querySelectorAll('[data-remove-source]').forEach(b=>b.onclick=()=>removeSource(b.dataset.removeSource))}
function openProject(){ $('#projectInput').value=state.project.name;$('#questionInput').value=state.project.question;$('#jurisdictionsInput').value=state.project.jurisdictions.join(', ');$('#startYearInput').value=state.project.startYear;$('#projectDialog').showModal() }
function saveProject(){const jurisdictions=$('#jurisdictionsInput').value.split(',').map(x=>x.trim()).filter(Boolean);if(!$('#projectInput').value.trim()||!$('#questionInput').value.trim()||!jurisdictions.length){toast('Add a name, question, and at least one jurisdiction.');return}state={project:{name:$('#projectInput').value.trim(),question:$('#questionInput').value.trim(),jurisdictions,startYear:Number($('#startYearInput').value)||2023},sources:[],claims:[],approved:false};persist();render();$('#projectDialog').close();toast('New research workspace created.')}
function openSource(){ $('#sourceDialog').showModal() }
function saveSource(){const title=$('#sourceTitleInput').value.trim(),publisher=$('#publisherInput').value.trim(),locator=$('#locatorInput').value.trim();if(!title||!publisher||!locator){toast('Title, publisher, and an exact locator are required.');return}state.sources.push({id:`source-${Date.now()}`,title,publisher,type:$('#sourceTypeInput').value,year:Number($('#sourceYearInput').value),locator,primary:$('#primaryInput').checked,direct:$('#directInput').checked,independent:$('#independentInput').checked});persist();render();$('#sourceDialog').close();toast('Source added to the library.')}
function prepareClaimSources(){ $('#claimJurisdictionInput').innerHTML=state.project.jurisdictions.map(j=>`<option>${escapeHtml(j)}</option>`).join('');$('#claimSourceInput').innerHTML=state.sources.map(s=>`<option value="${escapeHtml(s.id)}">${escapeHtml(s.title)}</option>`).join('')||'<option value="">No sources available</option>' }
function openClaim(jurisdiction='',dimension='status'){prepareClaimSources();$('#claimJurisdictionInput').value=jurisdiction||state.project.jurisdictions[0];$('#dimensionInput').value=dimension;$('#claimDialog').showModal()}
function saveClaim(){const subject=$('#subjectInput').value.trim(),value=$('#valueInput').value.trim(),text=$('#claimTextInput').value.trim(),sourceId=$('#claimSourceInput').value;if(!subject||!value||!text||!sourceId){toast('Add a subject, value, statement, and supporting source.');return}state.claims.push({id:`claim-${Date.now()}`,jurisdiction:$('#claimJurisdictionInput').value,subject,dimension:$('#dimensionInput').value,value,status:$('#statusInput').value,date:$('#dateInput').value,text,metric:$('#metricInput').value.trim()||undefined,sourceIds:[sourceId]});state.approved=false;persist();render();$('#claimDialog').close();toast('Claim linked to its source.')}
function inspectClaim(id){const c=linked.find(x=>x.id===id),d=$('#drawer');if(!c)return;d.innerHTML=`<button class="drawer-close">×</button><p class="eyebrow">CLAIM INSPECTOR</p><h2>${escapeHtml(c.text)}</h2><p><b>Support:</b> ${escapeHtml(c.support)}</p><h3>Evidence</h3>${c.evidence.map(s=>`<article><b>${escapeHtml(s.title)}</b><p>${escapeHtml(s.publisher)} · ${escapeHtml(s.locator)}</p><p>Quality ${sourceScore(s).grade} (${sourceScore(s).score}/100)</p></article>`).join('')||'<p>No evidence linked.</p>'}<button class="delete-action" data-delete-claim="${escapeHtml(c.id)}">Delete claim</button>`;d.classList.add('open');d.querySelector('.drawer-close').onclick=()=>d.classList.remove('open');d.querySelector('[data-delete-claim]').onclick=()=>{state.claims=state.claims.filter(x=>x.id!==id);persist();d.classList.remove('open');render();toast('Claim removed.')}}
function removeSource(id){if(state.claims.some(c=>c.sourceIds?.includes(id))){toast('Remove linked claims before deleting this source.');return}state.sources=state.sources.filter(s=>s.id!==id);persist();render();toast('Source removed.')}
function reportText(){return `${state.project.name}\n\n${state.project.question}\n\n${linked.filter(c=>c.support!=='unsupported').map(c=>`- ${c.text} [${c.evidence[0]?.title}, ${c.evidence[0]?.locator}]`).join('\n')}\n\nLimitations\n- ${cov.gaps.length} evidence cells remain uncovered.\n- ${contradictions.length} contradiction(s) remain visible.`}
function showReport(review=false){calculate();$('#reportTitle').textContent=review?'Contradiction review':state.project.name;$('#reportBody').innerHTML=`<p>${escapeHtml(state.project.question)}</p><h3>Supported findings</h3>${linked.filter(c=>c.support!=='unsupported').map(c=>`<p class="report-claim">${escapeHtml(c.text)} <small>[${escapeHtml(c.evidence[0]?.title||'No source')}, ${escapeHtml(c.evidence[0]?.locator||'no locator')}]</small></p>`).join('')||'<p>No supported findings yet.</p>'}<h3>Limitations</h3><p>${cov.gaps.length} coverage gaps and ${contradictions.length} contradiction(s) remain.</p>`;$('#reportDialog').showModal()}
function exportJson(){const blob=new Blob([JSON.stringify({...state,evaluation:{coverage:cov,contradictions}},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${state.project.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.json`;a.click();URL.revokeObjectURL(url);toast('Research data exported.')}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(window.policyToast);window.policyToast=setTimeout(()=>e.classList.remove('show'),2800)}
$('#newResearchBtn').onclick=openProject;$('#saveProjectBtn').onclick=saveProject;$('#addSourceBtn').onclick=openSource;$('#saveSourceBtn').onclick=saveSource;$('#addClaimBtn').onclick=()=>openClaim();$('#addClaimBtn2').onclick=()=>openClaim();$('#saveClaimBtn').onclick=saveClaim;$('#exportBtn').onclick=exportJson;$('#copyReportBtn').onclick=async()=>{await navigator.clipboard.writeText(reportText());toast('Report copied.')};$('#approveReportBtn').onclick=()=>{state.approved=true;persist();render();$('#reportDialog').close();toast('Report approved and saved.')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('aside nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.action==='report'||b.dataset.action==='approval')showReport(b.dataset.action==='approval');else document.getElementById(b.dataset.section||'overview').scrollIntoView({behavior:'smooth'})});
render();
